---
title: "Results"
author: "James Yang"
date: "2/19/2018"
output: html_document
---

**Results**

```{r, echo = FALSE}
set.seed(23)

library(ggplot2)
library(tidyr)
library(forcats)

plot_simulation <- function(N_input, k_input) {
  
  # run simulation given sample size and population size
  N <- N_input
  k <- k_input
  runs <- 10000
  mom_statistic <- numeric(runs)
  mle_statistic <- numeric(runs)
  custom1_statistic <- numeric(runs)
  custom2_statistic <- numeric(runs)
  
  for(i in 1:runs) {
    sample_values <- sample(1:N, k)
    mom_statistic[i] <- 2*mean(sample_values) - 1
    mle_statistic[i] <- max(sample_values)
    custom1_statistic[i] <- max(sample_values) + 
      (max(sample_values)^(k+1) + k)/((k+1)*max(sample_values)^k)
    custom2_statistic[i] <- max(sample_values) + min(sample_values) - 1
  }
  
  # functions that calculate MSE and Bias of estimators
  mse <- function(statistic) {
    return(var(statistic) + (mean(statistic) - N)^2)
  }
  bias <- function(statistic) {
    return(mean(statistic) - N)
  }
  
  # calculate properties of estimators
  stats <- list(mom_statistic, mle_statistic, custom1_statistic, custom2_statistic)
  mse_list <- unlist(lapply(stats, FUN = mse))
  var_list <- unlist(lapply(stats, FUN = var))
  bias_list <- unlist(lapply(stats, FUN = bias))
  names <- c("MoM", "MLE", "Custom 1", "Custom 2")
  
  # put into data frame and gather the estimator values
  params <- data.frame(estimators = names, MSE = mse_list, 
                       Variance = var_list, Bias = bias_list)
  params <- gather(params, key = stat, value = Value, MSE, Variance, Bias)

  # plot the line graph
  ggplot() +
    geom_line(data = params, aes(x = fct_inorder(estimators), y = Value, 
              group = fct_inorder(stat), color = fct_inorder(stat))) + 
    xlab("Estimators") +
    labs(color = "Properties") +
    ggtitle(paste("Properties of Estimators for Sample Size", k_input, 
                  "and Population Size", N_input))
}
```


```{r, echo = FALSE}
plot_simulation(200, 10)
```

