---
title: "Simulation Study"
author: "Kiya Govek"
date: "2/7/2018"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Simulation study

### Run simulation
```{r}
set.seed(175)
N <- 20
k <- 10
runs <- 10000
mom_statistic <- numeric(runs)
mle_statistic <- numeric(runs)
custom1_statistic <- numeric(runs)
custom2_statistic <- numeric(runs)
for(i in 1:runs) {
  sample_values <- sample(1:N, k)
  mom_statistic[i] <- 2*mean(sample_values) - 1
  mle_statistic[i] <- max(sample_values)
  custom1_statistic[i] <- max(sample_values) + (max(sample_values)^(k+1) + k)/((k+1)*max(sample_values)^k)
  custom2_statistic[i] <- median(sample_values) # do something here!!!
}
```

### Compare estimators
```{r}
# Mean squared error of MoM estimator
var(mom_statistic) + (mean(mom_statistic) - N)^2
# Mean squared error of ML estimator
var(mle_statistic) + (mean(mle_statistic) - N)^2
# Mean squared error of first custom estimator
var(custom1_statistic) + (mean(custom1_statistic) - N)^2
# Mean squared error of second custom estimator
var(custom2_statistic) + (mean(custom2_statistic) - N)^2
```

## Final estimate
```{r}
sample_values <- c(922, 299, 1106, 121, 1621, 1164, 1912, 937, 914, 593, 
                85, 1090, 1004, 139, 1451, 24, 267, 1045, 1062, 1274)
max(sample_values) + (max(sample_values)^(k+1) + k) / ((k+1)*max(sample_values)^k)

```